### PR TITLE
[RFR] Update to React 15

### PR DESCRIPTION
**Pull request by eschaefer**
- updates components from using deprecated `createClass()` method to ES6 classes
- updates React to `15.6.1`
- updates example to new syntax
- bumps version to `1.1.0`

### CODE REVIEW

**Comment by eschaefer** [comment]
ping @livmadsen @artibella @sigmarstern.

One of you will need to `npm publish` to update the package version on the npm registry :)

**Comment by eschaefer** [comment]
ping @edenspiekermann/devs?

**Comment by eschaefer** [comment]
ping @dsteinel ? 😺

**Review by dsteinel — APPROVED** [review]
👨🏻‍⚕️

**Comment by eschaefer** [comment]
@artibella @livmadsen @dsteinel does someone want to merge?

**Comment by eschaefer** [comment]
Hey @dsteinel @artibella @livmadsen someone needs to run `npm publish` with the espi npm account, or nobody will get the update 🎉 

NPM still sees the old version: https://www.npmjs.com/package/faster-react-tabs

**Pull request merged**
